# Generated by Django 3.2 on 2021-04-14 15:52

import app_todo.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Название')),
                ('important', models.BooleanField(default=False, verbose_name='Важная')),
                ('public', models.BooleanField(blank=True, default=False, verbose_name='Публичная')),
                ('create_at', models.DateTimeField(default=app_todo.models._get_default_date, verbose_name='Дата')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('draft', 'Отложено'), ('done', 'Выполнено')], default='draft', max_length=10, verbose_name='Состояние')),
                ('views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('message', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('rating', models.PositiveIntegerField(choices=[(0, 'Без оценки'), (1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], default=0, verbose_name='Оценка')),
                ('commentator', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Комментатор')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_todo.note', verbose_name='Заметка')),
            ],
            options={
                'ordering': ('create_at',),
            },
        ),
    ]
