# Generated by Django 3.2 on 2021-04-09 15:55

import app_todo.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Название')),
                ('important', models.BooleanField(default=False, verbose_name='Важная')),
                ('public', models.BooleanField(blank=True, default=False, verbose_name='Публичная')),
                ('create_at', models.DateField(default=app_todo.models._get_default_date, verbose_name='Дата')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('draft', 'Отложено'), ('done', 'Выполнено')], default='draft', max_length=10, verbose_name='Состояние')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'ordering': ('-create_at',),
            },
        ),
    ]
