# Generated by Django 3.2 on 2021-04-14 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='readers',
            field=models.ManyToManyField(related_name='notes', through='app_todo.Comment', to=settings.AUTH_USER_MODEL, verbose_name='Читатели'),
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_notes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
